[package]
name = "pkgtool"
version = "0.1.0"
authors = ["tkaria <tkaria.info@gmail.com>"]
edition = "2018"
description = "dpkg manegement tool"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.20.3"
